import assert from "node:assert/strict";
import {
	mkdir,
	mkdtemp,
	readdir,
	readFile,
	rename,
	rm,
	symlink,
	writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { DefaultResourceLoader, SettingsManager } from "@earendil-works/pi-coding-agent";
import { test } from "vitest";

const packageRoot = resolve("packages/pi-subagents");
const builderUrl = pathToFileURL(join(packageRoot, "scripts/build-runtime.mjs")).href;

type Metadata = {
	outputs?: Record<
		string,
		{
			entryPoint?: string;
			inputs?: Record<string, unknown>;
			imports?: Array<{ external?: boolean; path: string }>;
		}
	>;
};
type Builder = {
	buildRuntime(options?: {
		outputDirectory?: string;
		validateOutput?: (directory: string) => Promise<void>;
	}): Promise<Metadata>;
	validateEagerGraph(metadata: Metadata): { eagerInputs: Set<string>; eagerOutputs: Set<string> };
	validateGeneratedFiles(directory: string): Promise<void>;
	publishRuntime(
		staging: string,
		output: string,
		operations?: { renamePath?: typeof rename },
	): Promise<void>;
};

async function builder(): Promise<Builder> {
	return (await import(`${builderUrl}?test=${crypto.randomUUID()}`)) as Builder;
}

test("runtime builds are deterministic, mapped, external, and contain no retained graph", async () => {
	const runtime = await builder();
	const root = await mkdtemp(join(packageRoot, ".pi-subagents-build-test-"));
	try {
		const first = join(root, "first");
		const second = join(root, "second");
		const firstMetadata = await runtime.buildRuntime({ outputDirectory: first });
		await mkdir(second, { recursive: true });
		await writeFile(join(second, "stale.ts"), "stale");
		const secondMetadata = await runtime.buildRuntime({ outputDirectory: second });
		assert.deepEqual(await snapshot(first), await snapshot(second));
		assert.equal((await files(second)).includes("stale.ts"), false);
		for (const metadata of [firstMetadata, secondMetadata]) {
			const graph = runtime.validateEagerGraph(metadata);
			const inputs = [...graph.eagerInputs].join("\n");
			assert.match(inputs, /src\/bounded-subagents\.ts/u);
			assert.doesNotMatch(
				inputs,
				/registry|persistence|peer-|stateful|settings|workspace|usage-recording/u,
			);
			for (const output of Object.values(metadata.outputs ?? {})) {
				assert.equal(
					Object.keys(output.inputs ?? {}).some((value) => value.includes("node_modules/")),
					false,
				);
			}
		}
		assert.deepEqual(await files(first), ["index.ts", "index.ts.map"]);
		const source = await readFile(join(first, "index.ts"), "utf8");
		assert.match(source, /^\/\/ @generated by scripts\/build-runtime\.mjs/u);
		assert.doesNotMatch(source, /child-peer-bridge|subagent_send|subagent_mailbox/u);
		await runtime.validateGeneratedFiles(first);
	} finally {
		await rm(root, { recursive: true, force: true });
	}
});

test("generated runtime loads and reloads through DefaultResourceLoader", async () => {
	const runtime = await builder();
	const root = await mkdtemp(join(packageRoot, ".pi-subagents-build-test-"));
	const agentDir = join(root, "agent");
	const output = join(root, "dist");
	try {
		await runtime.buildRuntime({ outputDirectory: output });
		await mkdir(agentDir);
		const loader = new DefaultResourceLoader({
			cwd: root,
			agentDir,
			settingsManager: SettingsManager.inMemory({}),
			additionalExtensionPaths: [join(output, "index.ts")],
		});
		for (let attempt = 0; attempt < 2; attempt += 1) {
			await loader.reload();
			const loaded = loader.getExtensions();
			assert.deepEqual(loaded.errors, []);
			assert.equal(loaded.extensions.length, 1);
			assert.deepEqual(
				[...(loaded.extensions[0]?.tools.keys() ?? [])],
				["subagent_spawn", "subagent_await", "subagent_cancel", "subagent_inspect"],
			);
			assert.ok(loaded.extensions[0]?.commands.has("subagents"));
		}
	} finally {
		await rm(root, { recursive: true, force: true });
	}
});

test("runtime build rejects destructive or symlink-escaped output paths", async () => {
	const runtime = await builder();
	const outside = await mkdtemp(join(tmpdir(), "pi-subagents-build-outside-"));
	const linked = join(packageRoot, `.pi-subagents-build-test-link-${crypto.randomUUID()}`);
	try {
		await assert.rejects(runtime.buildRuntime({ outputDirectory: packageRoot }), /must be inside/u);
		await assert.rejects(
			runtime.buildRuntime({ outputDirectory: join(outside, "dist") }),
			/must be inside/u,
		);
		await symlink(outside, linked, "dir");
		await assert.rejects(
			runtime.buildRuntime({ outputDirectory: join(linked, "dist") }),
			/symlink/u,
		);
	} finally {
		await rm(linked, { recursive: true, force: true });
		await rm(outside, { recursive: true, force: true });
	}
});

test("failed validation and publication preserve the previous runtime", async () => {
	const runtime = await builder();
	const root = await mkdtemp(join(packageRoot, ".pi-subagents-build-test-"));
	try {
		const output = join(root, "dist");
		await mkdir(output);
		await writeFile(join(output, "previous.ts"), "previous");
		await assert.rejects(
			runtime.buildRuntime({
				outputDirectory: output,
				validateOutput: async () => {
					throw new Error("validation failed");
				},
			}),
			/validation failed/u,
		);
		assert.deepEqual(await files(output), ["previous.ts"]);

		const staging = join(root, "staging");
		await mkdir(staging);
		await writeFile(join(staging, "next.ts"), "next");
		let calls = 0;
		await assert.rejects(
			runtime.publishRuntime(staging, output, {
				renamePath: async (source, destination) => {
					calls += 1;
					if (calls === 2) throw new Error("publication failed");
					await rename(source, destination);
				},
			}),
			/publication failed/u,
		);
		assert.equal(await readFile(join(output, "previous.ts"), "utf8"), "previous");
	} finally {
		await rm(root, { recursive: true, force: true });
	}
});

async function files(directory: string, prefix = ""): Promise<string[]> {
	const result: string[] = [];
	for (const entry of await readdir(join(directory, prefix), { withFileTypes: true })) {
		const relative = join(prefix, entry.name);
		if (entry.isDirectory()) result.push(...(await files(directory, relative)));
		else result.push(relative.replaceAll("\\", "/"));
	}
	return result.sort();
}

async function snapshot(directory: string): Promise<Record<string, string>> {
	const result: Record<string, string> = {};
	for (const file of await files(directory))
		result[file] = await readFile(join(directory, file), "base64");
	return result;
}
